language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake ci:travis && bundle exec rake spec:arel ENGINE=Arel"
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: jruby-head
    - rvm: 2.0.0
before_script:
  - psql -c 'create database "dm-mapper_test";' -U postgres
notifications:
  email:
    - piotr.solnica@gmail.com
